---
  - name: installation prérequis
    shell: apt install software-properties-common -y

  - name: installer logiciels
    apt:
      name: "{{ item }}"
    with_items:
      - sudo
      - apache2
      - php8.2
      - libapache2-mod-php8.2
      - libapache2-mod-security2
      - php8.2-mysql
      - php8.2-gd
      - php8.2-xml
      - php8.2-mbstring
      - php8.2-gettext
      - php8.2-zip
      - php8.2-curl
    
  - name: Ajout syslog-ng default
    template:
      src: syslog-ng.j2
      dest: /etc/default/syslog-ng
      owner: www-data
      group: www-data
      mode: 0644

  - name: Changer droits des fichiers
    file:
      path: /etc/default/syslog-ng
      owner: root
      group: root
      mode: 0640
    
  - name: clean apt
    shell: apt-get clean -y

  - name: supprimer le cache
    shell: "rm -rf /var/lib/apt/lists/*"

  - name: nettoyage
    shell: apt-get -y autoremove
    
  - name: lien PHP 7 vers alternative
    shell: ln -sfn /usr/bin/php8.2 /etc/alternatives/php

  - name: copier le vhost
    template:
      src: vhost.conf.j2
      dest: /etc/apache2/sites-available/vhost.conf
      
  - name: apache2 dis en vh
    shell: |
      a2dissite 000-default
      a2ensite vhost
    notify: Start Apache

  - name: Creer un index.html customisé
    copy:
      content: "Welcome to {{ ansible_hostname }}!"
      dest: /var/www/html/index.html
    notify: Reload Apache
    
  - name: Copy Tomcat context.xml from local to remote with permissions
    copy:
      src: files/fichier.txt
      dest: /var/www/html/fichier.txt
      owner: www-data
      group: www-data
      mode: '0640'

#  - name: redémarrer apache2
#    shell: service apache2 restart

